// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJJilD98rFGz9-9Zck1wzVUdqd7HqcjnI',
    appId: '1:816754578812:ios:286b71a5c91186215cc0f9',
    messagingSenderId: '816754578812',
    projectId: 'autocompareai-95454',
    storageBucket: 'autocompareai-95454.firebasestorage.app',
    iosClientId: '816754578812-l421kvh4qe4cl8a9bgq641ci6rj437mk.apps.googleusercontent.com',
    iosBundleId: 'com.example.autocompareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVY0sNvwsgWB93IuFwEIgilOsJhLbQ55c',
    appId: '1:816754578812:web:46eaceb84cf94aee5cc0f9',
    messagingSenderId: '816754578812',
    projectId: 'autocompareai-95454',
    authDomain: 'autocompareai-95454.firebaseapp.com',
    storageBucket: 'autocompareai-95454.firebasestorage.app',
    measurementId: 'G-KGCF4ZWVFY',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVY0sNvwsgWB93IuFwEIgilOsJhLbQ55c',
    appId: '1:816754578812:web:46eaceb84cf94aee5cc0f9',
    messagingSenderId: '816754578812',
    projectId: 'autocompareai-95454',
    authDomain: 'autocompareai-95454.firebaseapp.com',
    storageBucket: 'autocompareai-95454.firebasestorage.app',
    measurementId: 'G-KGCF4ZWVFY',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJJilD98rFGz9-9Zck1wzVUdqd7HqcjnI',
    appId: '1:816754578812:ios:286b71a5c91186215cc0f9',
    messagingSenderId: '816754578812',
    projectId: 'autocompareai-95454',
    storageBucket: 'autocompareai-95454.firebasestorage.app',
    iosClientId: '816754578812-l421kvh4qe4cl8a9bgq641ci6rj437mk.apps.googleusercontent.com',
    iosBundleId: 'com.example.autocompareApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOL8KW4_8n0XEPuiuQkxgv__UmdrYwvg0',
    appId: '1:816754578812:android:47d400fbcf0f71d75cc0f9',
    messagingSenderId: '816754578812',
    projectId: 'autocompareai-95454',
    storageBucket: 'autocompareai-95454.firebasestorage.app',
  );

}